language: scala
sudo: false

jdk:
  - openjdk8
  - openjdk7

scala:
  - 2.10.4
  - 2.11.2

script:
  - sbt -sbt-version 0.13.8 -scala-version $TRAVIS_SCALA_VERSION 'tests/test-only -- xonly exclude contrib'

